books:
  outputs:
    dev:
      type: duckdb
      path: reports/sources/books/book_rating.duckdb
      threads: 4

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev