
version: 2



models:
  - name: stg_books
    description: "Table of books. Raw data from the source with a timestamp of data ingestion and the source url."
    columns:
      - name: ISBN
        description: "ISBN of the book"
        data_tests:
          - not_null
      - name: Book-Title
        description: "Title of the book"
        data_tests:
          - not_null
      - name: Book-Author
        description: "Author of the book"
        data_tests:
          - not_null
      - name: Year-Of-Publication
        description: "Year of publication of the book"
        data_tests:
          - not_null
      - name: Publisher
        description: "Publisher of the book"
      - name: Image-URL-S
        description: "Small image URL of the book"
      - name: Image-URL-M
        description: "Medium image URL of the book"
      - name: Image-URL-L
        description: "Large image URL of the book"
      - name: ts
        description: "Timestamp of data ingestion"
        data_type: timestamp
        data_tests:
          - not_null
      - name: source_url
        description: "Source URL of the data file"
        data_tests:
          - not_null
  - name: stg_book_rating
    description: "Ratings of the books by individual users. Raw data from the source with a timestamp of data ingestion and the source url."
    columns:
      - name: ISBN
        description: "ISBN of the book"
        data_type: string
        data_tests:
          - not_null
      - name: ts
        description: "Timestamp of data ingestion"
        data_type: timestamp
        data_tests:
          - not_null
      - name: source_url
        description: "Source URL of the data file"
        data_type: string
        data_tests:
          - not_null
  - name: stg_filtered_book_ratings
    description: "Filtered book ratings table"
    columns:
      - name: UserID
        description: "ID of the user who rated the book"
        data_type: integer
      - name: ISBN
        description: "ISBN of the book"
        data_type: string
      - name: BookRating
        description: "Rating of the book"
        data_type: integer
        data_tests:
          - not_null
      - name: ts
        description: "Timestamp of data ingestion"
        data_type: timestamp
        data_tests:
          - not_null
      - name: source_url
        description: "Source URL of the data file"
        data_type: string
        data_tests:
          - not_null
  - name: stg_normalized_book
    description: "Normalized book table. The ISBN is unique for each book. Title, author, ISBN are normalized."
    columns:
      - name: BookTitle
        description: "Title of the book"
        data_type: string
        data_tests:
          - not_null
      - name: BookAuthor
        description: "Author of the book"
        data_type: string
        data_tests:
          - not_null
      - name: LowerISBN
        description: "Lowercase ISBN of the book"
        data_type: string
        data_tests:
          - not_null
          - unique
      - name: ShortenedCleanedISBN
        description: "Shortened cleaned ISBN of the book. We keep just the digits of the ISBN and 'x' character if present. We keep just the first 9 digits of the cleaned ISBN."
        data_type: string
        data_tests:
          - not_null
          - unique
      - name: NormBookTitle
        description: "Normalized title of a book. All symbols except characters and numbers are removed"
        data_type: string
      - name: NormBookAuthor
        description: "Normalized author of a book. We keep just frist and last part of the name"
        data_type: string
